main: dev.cibmc.spigot.minecraftplugin.App
name: minecraftplugin
version: 0.1
Author: Hai Shi, Edmond Li, Edward He
Description: A plugin that we made for fun lol
commands:
      test:
            description: Test command lol
            usage: /test
            permissions: minecraftplugin.test   
            permission-message: you dont have the minecraftplugin.test permission.
      testItem:
            description: test command for items
            usage: /testItem
            permissions: minecreaftplugin.testItem
            permission-message: you dont have the minecraftplugin.testItem permission.